// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketFlow.Contexts.Sales.Infrastructure.Data;

#nullable disable

namespace TicketFlow.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20260608033331_CorrecaoPedidos")]
    partial class CorrecaoPedidos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketFlow.Contexts.Sales.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("TicketFlow.Contexts.Sales.Domain.Entities.TemporaryReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_Reservations_ClienteId");

                    b.HasIndex("EventoId")
                        .HasDatabaseName("IX_Reservations_EventoId");

                    b.ToTable("TemporaryReservations", (string)null);
                });

            modelBuilder.Entity("TicketFlow.Contexts.Sales.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenPagamento")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("IX_Transactions_PedidoId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Ingresso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("TicketFlow.Contexts.Sales.Domain.Entities.Order", b =>
                {
                    b.OwnsMany("TicketFlow.Contexts.Sales.Domain.Entities.OrderItem", "Itens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("EventoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("PrecoUnitario")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("OrderId");

                            b1.ToTable("OrderItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("TicketFlow.Contexts.Sales.Domain.Entities.TemporaryReservation", b =>
                {
                    b.OwnsOne("TicketFlow.Contexts.Sales.Domain.ValueObjects.PeriodoValidade", "Validade", b1 =>
                        {
                            b1.Property<Guid>("TemporaryReservationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CriadaEm")
                                .HasColumnType("datetime2")
                                .HasColumnName("ValidadeCriadaEm");

                            b1.Property<DateTime>("ExpiraEm")
                                .HasColumnType("datetime2")
                                .HasColumnName("ValidadeExpiraEm");

                            b1.HasKey("TemporaryReservationId");

                            b1.ToTable("TemporaryReservations");

                            b1.WithOwner()
                                .HasForeignKey("TemporaryReservationId");
                        });

                    b.Navigation("Validade")
                        .IsRequired();
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Ingresso", b =>
                {
                    b.HasOne("TicketFlow.Contexts.Sales.Domain.Entities.Order", null)
                        .WithMany("Ingressos")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("TicketFlow.Contexts.Sales.Domain.Entities.Order", b =>
                {
                    b.Navigation("Ingressos");
                });
#pragma warning restore 612, 618
        }
    }
}
